management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    baggage:
      remote-fields:
      - remote-field1
      - remote-field2
      - remote-field3
      - remote-field4
      - remote-field5
      - remote-field6
      correlation:
        fields:
        - correlation-field1
        - correlation-field2
        - correlation-field3
        - correlation-field4
        - correlation-field5
        - correlation-field6