management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
# turn off zipkin
      probability: 0.0
    baggage:
      remote-fields:
      - remote-field1
      - remote-field2
      - remote-field3
      - remote-field4
      - remote-field5
      - remote-field6
      correlation:
        fields:
        - correlation-field1
        - correlation-field2
        - correlation-field3
        - correlation-field4
        - correlation-field5
        - correlation-field6
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      connect-timeout: 2000
      read-timeout: 2000
      #enabled: false